### ISSUE TITLE
Many-to-many relation insert not working

### ISSUE THREAD

**Issue by JValck** [alsofronie/eloquent-uuid#11]
I'm using the `UuidBinaryModelTrait` for all my models.
Unfortunately the `sync` method (provided by Laravel) doesn't seem to generate a binary Uuid.

To be more concrete:
I have a class `User` and a class `Organisation`. A `User` has multiple organisations and an `Organisation` has multiple users. This relationship is saved in the database table `user_organisations`, which is where the problem occurs. When I call `$user->organisations()->sync([$o_id, $o_id2])` to insert a new row, I get an Internal Server Error indicating that the primary key already exists. When I verify the `user_organisations` table, I noticed that the only row in the table has a key `0x000000000000000000000000000000`.

**Comment by alsofronie** [comment]
I will look into it as soon as possible. Can you write some unit tests for this issue?

**Comment by alsofronie** [comment]
It seems there is something wrong in other part of your code. I've just included tests for many to many and it's working exactly as expected.

**Comment by JValck** [comment]
I just checked your tests. In my code I have almost exactly the same as you. The only exception is the database. At line [527](https://github.com/alsofronie/eloquent-uuid/blob/master/tests/EloquentUuidTest.php#L527) you commented out the primary id creation which is exactly what causes the issue. 

In my DDL I'm creating a binary primary key in that table as well. This primary key is not a combination of two columns. Unfortunately this id is never generated.

**Comment by alsofronie** [comment]
Oh, you should not have a key in that database, unless you attack an eloquent model to the relation, in which case the id will be generated (but not with the `sync` or `attach` method. It is true, with an auto incremented key you CAN have the relationship working but this is a database feature, not a Laravel (or Eloquent) feature.

In my code I had to comment that line because, according to [sqlite documentation](http://sqlite.org/faq.html#q11) you cannot alter table to add a primary key. That's not the case with MySQL, though.

**Comment by alsofronie** [comment]
You cannot have a code generated id on a table if you are not attaching a model to it. The primary key works flawlessly in MySQL, so `sync`, `detach` and `attach` functions work.

**Comment by JValck** [comment]
I just ran your tests with MySQL. I modified the DB setup to test the id generation. (Line 528 + 529).
However the many-to-many test still fails.
[Here is the Gist](https://gist.github.com/JValck/4d39c8961e8a1eb016a1f91124172bf8)

Can you please clarify how to bind the model to the table in this case? Should I do something with the [pivot](https://laravel.com/api/5.2/Illuminate/Database/Eloquent/Relations/Pivot.html) to allow simple id generation?

**Comment by alsofronie** [comment]
The problem with your setup is you cannot have a UUID (code generated id) for a pivot table if you do not have a model attached to the pivot table. To clarify, let's use `User` and `Role` models with many to many relationships: a user can have multiple roles, a role can have (can be assigned to) multiple users.

You have three tables: `users`, `roles` and `role_user`.

### Option 1 - remove the id for the pivot.

This is, in my opinion, the correct approach but it can vary depending on your setup.
In `role_user` you will have `user_id` and `role_id`, with a primary key on both fields (you cannot have the same user on the same role twice). There is no ID here. This will correctly function with `attach()`, `detach()` and `sync()` Eloquent models.

### Option 2 - attach a model to the pivot (and you will not consider it pivot anymore, but a separate model)

You can have the `id` on your `user_role` table and you must have a `UserRole` model that will correctly generate the `id` for you. In this case, you will not have a direct relationship between `User` and `Role` but both models will be linked through `hasMany()` an `belongsTo()` with `UserRole` model.

**Comment by JValck** [comment]
Thanks for the clarification. I ended up with option 1.
