### ISSUE TITLE
FindOrFail support

### ISSUE THREAD

**Issue by carauzs** [alsofronie/eloquent-uuid#15]
Hi, it's possible to use findOrFail in the same way as find with both the binary version or the string (bin2hex) version???

**Comment by golinmarq** [comment]
@carauzs I created a PR for this but it still pending

**Comment by carauzs** [comment]
@golinmarq great :) I think we have to wait...

**Comment by golinmarq** [comment]
@carauzs you don't have to. The PR was approved  =)
