### ISSUE TITLE
Boot method on Model

### ISSUE THREAD

**Issue by stefensuhat** [alsofronie/eloquent-uuid#18]
I love this package make it easier to save my ID.

Found a problem if I have method boot at my model like example:

```
protected static function boot()
{
    parent::boot();

    static::addGlobalScope('follows_count', function (Builder $builder) {
        $builder->withCount('follows');
    });
}
```

The eloquent-uuid won't run if I create new instance. If I remove the boot method it will work properly. 

Any solution?

**Comment by elliotwms** [comment]
Look at [this StackOverflow answer](http://stackoverflow.com/a/11939306/3759812).

Basically in the model you want to override the boot method in you'll need to change how you `use` the trait. For example it should look like this:

``` php
use UuidModelTrait {
    boot as traitBoot
}
```

Then you'll need to change how you're calling `parent::boot()` so you're instead calling `self::traitBoot()`, which will call your `parent::boot()` for you
