### ISSUE TITLE
creating() isn't getting called

### ISSUE THREAD

**Issue by skeemer** [alsofronie/eloquent-uuid#22]
I've tried implementing this and it isn't working for me. My model does not have any boot stuff added, so there shouldn't be any conflicts. The methodbootUuidModelTrait() gets called, but I'm getting a SQL error before static::creating() is called.

    SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `sessions` (`user_id`, `updated_at`, `created_at`) values (8, 2016-11-10 21:20:49, 2016-11-10 21:20:49))

````
<?php
namespace Example\Models;

use Illuminate\Database\Eloquent\Model;
use Alsofronie\Uuid\UuidModelTrait;

class Session extends Model {
  use UuidModelTrait;
}
````
````
$session = new \Example\Models\Session();
$session->user_id = 8;
$session->save();
````
````
CREATE TABLE `sessions` (
  `id` char(36) NOT NULL,
  `user_id` int(11) NOT NULL,
  `expires_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
````

**Comment by alsofronie** [comment]
It's very strange because there is a scenario in the tests almost identical to your setup. I'll look into it.

**Comment by skeemer** [comment]
FYI, the illuminate/database version is 5.3.16.

```
  "require": {
    "slim/slim": "^3.5",
    "illuminate/database": "^5.3",
    "illuminate/filesystem": "^5.3",
    "phpmailer/phpmailer": "~6.0",
    "robmorgan/phinx": "^0.6.5",
    "dflydev/fig-cookies": "^1.0",
    "alsofronie/eloquent-uuid": "dev-master"
  }
```

**Comment by skeemer** [comment]
I haven't gotten a chance to test it yet, but probably related to this: https://github.com/laravel/framework/issues/7339#issuecomment-73462204

Basically EventDispatcher wasn't loading and therefore observers not getting called.

**Comment by skeemer** [comment]
The solution in that linked comment did work. Your implementation works great!
