### ISSUE TITLE
Can we get a new release including the bootTrait() fixes?

### ISSUE THREAD

**Issue by RBastianini** [alsofronie/eloquent-uuid#23]
I was looking forward to use this library since it's the only one I found that takes into consideration the DB storage optimization for UUIDs.
However, the latest release does not include pull request #6 yet, so I have to write some funny code to make the trait work fine with custom boot logic.

I can't use the master branch or the development release, I am required to use normal releases available from packagist. Is there any chance of a newer release including this fix coming in the near future?
Thanks.

**Comment by stefensuhat** [comment]
+1

**Comment by alsofronie** [comment]
I've made the [1.0.5](https://github.com/alsofronie/eloquent-uuid/releases/tag/v1.0.5) release. Hope it helps.
