### ISSUE TITLE
UuidBinaryModelTrait::toArray() throes exception with one-to-many relations.

### ISSUE THREAD

**Issue by RBastianini** [alsofronie/eloquent-uuid#24]
In the new 1.0.5 release there is the following error, when attempting to call `toArray()` on an object using the UuidBinaryModelTrait and having at least a one-to-many relation:

```
preg_match() expects parameter 2 to be string, array given
(...)/vendor/alsofronie/eloquent-uuid/src/UuidBinaryModelTrait.php Line 94
```

### Solution
Probably the right solution would be to check if `$key == $this->primaryKey` instead of checking with a regex. That would ensure the conversion would be done only for the primary key (which is the only key we know of that contains binary data).
Yes, there might be more than one key containing binary data (for example in a one-to-one relation, there could be a reference to another model using the UuidBinaryModelTrait), but I think at that point it's the developer's duty to use `$model->$hidden` to hide them (or to provide an accessor method to properly format them). Otherwise, just check that the value is actually a string before using the regex.
If you like my solution I can try to make a pull request during the weekend to fix the bug.

### Quick and dirty workaround
In the meantime I have implemented the following workaround, which disables the `UuidBinaryModelTrait::toArray()` method by renaming it and by using the base `Model::toArray()` one.
```php
<?php

namespace Blah;

use Alsofronie\Uuid\UuidBinaryModelTrait;
use Illuminate\Database\Eloquent\Model;

trait BinaryUUIDTrait
{
	use UuidBinaryModelTrait {
		// Rename the trait's toArray method so that the parent one can be used.
		UuidBinaryModelTrait::toArray as _brokenToArray;
	}

	/**
	 * @see Model::toArray()
	 * @return array
	 */
	public function toArray()
	{
		// Forward the call to the parent method.
		return parent::toArray();
	}
}
```
If you copy-paste it to a file, and use this trait instead of the original one, `$model->toArray()` works again (although you will see binary junk in the array. :)

**Comment by alsofronie** [comment]
Should be working now.
