### ISSUE TITLE
anyone has experience using this with laravel 5.4 

### ISSUE THREAD

**Issue by MordiSacks** [alsofronie/eloquent-uuid#27]
anyone has experience using this with laravel 5.4 
working ? broken? issues?
Thanks

**Comment by alsofronie** [comment]
I'll run the tests against laravel 5.4 later today. If there are no issues, I will make a new release with the proper documentation.

**Comment by tpetry** [comment]
Already using it in a few projects with 5.4, works perfectly :)

**Comment by alsofronie** [comment]
I confirm, I'm using it in 5.4 as well.
